import os

APP_CONFIG_PATH = os.environ.get("APP_CONFIG_PATH")

AUTHORIZER_TOKEN_PAYLOAD_LENGTH = 2
AUTHORIZER_TOKEN_IDENTIFIER_DEVICE = os.environ.get("AUTHORIZER_TOKEN_IDENTIFIER_DEVICE", "DeviceToken")
AUTHORIZER_TOKEN_IDENTIFIER_USER = os.environ.get("AUTHORIZER_TOKEN_IDENTIFIER_USER", "JWT")

USER_POOL_ID = os.environ.get("USER_POOL_ID")
USER_POOL_APP_CLIENT_ID = os.environ.get("USER_POOL_APP_CLIENT_ID")
